### ISSUE TITLE
crash when try to change flash time in options.  

### ISSUE THREAD

**Issue by ELY3M** [nizhogor/AlarmClock#1]
I will fork the source to my github and try to fix.  
I wanted the light to flash very fast like strobe.

**Comment by ELY3M** [comment]
12-23 07:38:04.897 25031-25652/? E/AndroidRuntime: FATAL EXCEPTION: Timer-0
                                                   Process: com.nizhogor.flashalarm, PID: 25031
                                                   java.lang.RuntimeException: Camera is being used after Camera.release() was called
                                                       at android.hardware.Camera.native_getParameters(Native Method)
                                                       at android.hardware.Camera.getParameters(Camera.java:1996)
                                                       at com.nizhogor.flashalarm.e$a.run(Unknown Source)
                                                       at java.util.Timer$TimerImpl.run(Timer.java:284)

**Comment by nizhogor** [comment]
Ely, thanks for your code. I've seen your email and will release within a couple of days. Could you please elaborate on what steps you took before you saw this exception?
